Repository honeycombio/honeycomb-network-agent, pull requests merged in 2023-12, with the labels that each got.

#321 maint: Make smoke tests more reliable
  Makefile
  smoke-tests/echoserver.yaml
Labels: type: maintenance, version: no bump

#322 rel: Prepare v0.1.0-beta release
  CHANGELOG.md
  main.go
Labels: version: bump minor, type: maintenance, no-changelog

#327 maint: update curl in smoke tests
  smoke-tests/smoke-job.yaml
  smoke-tests/verify.bats
Labels: type: maintenance, version: no bump

#325 maint: update codeowners to pipeline
  .github/CODEOWNERS
  .github/workflows/add-to-project-v2.yml
Labels: type: maintenance, version: no bump, no-changelog

#330 maint: update codeowners to pipeline-team
  .github/CODEOWNERS
Labels: type: maintenance

#326 maint: add deps and docs to maintenance in release
  .github/release.yml
Labels: type: maintenance, no-changelog

#331 feat: add honeycomb resource attributes
  handlers/libhoney_event_handler.go
  handlers/otel_handler.go
  smoke-tests/verify.bats
Labels: type: enhancement, version: bump minor, type: maintenance

#332 rel: Prepare the v0.2.0-beta release
  CHANGELOG.md
  main.go
Labels: type: maintenance, no-changelog
