Repository honeycombio/honeycomb-network-agent, pull requests merged in 2023-10, with the labels that each got.

#254 feat: Only keep HTTP headers we want to keep
  assemblers/tcp_reader.go
  assemblers/tcp_reader_test.go
Labels: type: bug

#243 docs: Add design section to readme
  README.md
  agent_design.png
Labels: type: documentation

#252 docs: update greetings example service for easier testing
  smoke-tests/greetings.yaml
Labels: type: documentation

#258 fix: Don't send durations when they are not from actual capture times
  handlers/libhoney_event_handler.go
  handlers/libhoney_event_handler_test.go
Labels: type: bug

#265 fix: skip key validation if endpoint is different
  config/config.go
  main.go
  smoke-tests/deployment.yaml
Labels: type: bug

#260 feat: Don't add k8s attributes when source/destination IP matches agent IP
  handlers/libhoney_event_handler.go
  utils/cached_k8s_client.go
  utils/cached_k8s_client_test.go
  utils/k8sutils.go
Labels: type: enhancement

#259 feat: Add config option to set additional attributes on all events
  config/config.go
  config/config_test.go
  handlers/libhoney_event_handler.go
  smoke-tests/deployment.yaml
  utils/env.go
Labels: type: enhancement

#266 maint: Reduce docker image size
  Dockerfile
Labels: type: maintenance

#267 rel: Prepare v0.0.20-alpha release
  CHANGELOG.md
  main.go
Labels: type: maintenance, no-changelog

#268 feat: Add opt-in config option for HTTP URL
  config/config.go
  config/config_test.go
  handlers/libhoney_event_handler.go
  handlers/libhoney_event_handler_test.go
  smoke-tests/deployment.yaml
Labels: type: enhancement

#270 maint: even smaller image size with no cached APT repo lists
  Dockerfile
Labels: type: maintenance

#269 feat: remove request URI query params from emitted url.path
  handlers/libhoney_event_handler.go
  handlers/libhoney_event_handler_test.go
Labels: type: enhancement

#274 maint: include k8s vars in quickstart and add resource limits to test manifest
  examples/quickstart.yaml
  smoke-tests/deployment.yaml
Labels: type: documentation, type: maintenance

#271 maint: Refactor packet processing to allow different event types
  assemblers/event.go
  assemblers/http_event.go
  assemblers/http_parser.go
  assemblers/http_parser_test.go
  assemblers/parser.go
  assemblers/tcp_assembler.go
  assemblers/tcp_reader.go
  assemblers/tcp_stream.go
  assemblers/tcp_stream_factory.go
  handlers/event_handler.go
  handlers/libhoney_event_handler.go
  handlers/libhoney_event_handler_test.go
  main.go
Labels: type: maintenance

#275 rel: prepare v0.0.21-alpha
  CHANGELOG.md
  main.go
Labels: type: maintenance

#279 docs: reminder to update docs when releasing
  RELEASING.md
Labels: type: documentation, no-changelog

#276 feat: capture more types of HTTP requests
  config/config.go
  config/config_test.go
Labels: type: enhancement

#283 fix: append agent info to user-agent
  handlers/libhoney_event_handler.go
Labels: type: bug, version: bump patch

#281 feat: Enable HTTP URL recording by default
  config/config.go
  config/config_test.go
Labels: type: enhancement

#277 feat: Add configurable list of HTTP headers to extract
  README.md
  assemblers/http_parser.go
  assemblers/http_parser_test.go
  assemblers/tcp_stream.go
  config/config.go
  config/config_test.go
  utils/env.go
Labels: type: enhancement

#284 rel: prepare v0.0.22-alpha
  CHANGELOG.md
  main.go
Labels: type: maintenance, no-changelog

#285 maint: Tidy start-up logging
  assemblers/tcp_assembler.go
  debug/debug_service.go
Labels: type: maintenance

#286 maint: update smoke test deployment for new env vars
  README.md
  smoke-tests/deployment.yaml
Labels: type: maintenance

#289 fix: add headers to honeycomb event
  handlers/libhoney_event_handler.go
  handlers/libhoney_event_handler_test.go
Labels: type: bug

#290 feat: Add OTLP handler to send events using OpenTelemetry
  config/config.go
  go.mod
  go.sum
  handlers/event_handler.go
  handlers/libhoney_event_handler.go
  handlers/libhoney_event_handler_test.go
  handlers/otel_handler.go
  handlers/otel_handler_test.go
  main.go
  smoke-tests/deployment.yaml
  utils/cached_k8s_client.go
  utils/cached_k8s_client_test.go
Labels: type: enhancement

#296 feat: Sanitise headers to OTel semconv and add as separate fields/attributes
  Makefile
  handlers/event_handler.go
  handlers/libhoney_event_handler.go
  handlers/libhoney_event_handler_test.go
  handlers/otel_handler.go
  handlers/otel_handler_test.go
Labels: type: enhancement

#298 fix: Update OTel header tests to use contains instead of comparing slices directly
  handlers/otel_handler_test.go
Labels: type: bug

#300 rel: prep v0.0.23-alpha
  CHANGELOG.md
  go.mod
  main.go
Labels: type: maintenance, no-changelog

#299 maint: Add otel dependabot group
  .github/dependabot.yml
Labels: type: maintenance

#293 feat: Detect and use OTel trace context for agent spans when handling HTTP events
  README.md
  config/config.go
  config/config_test.go
  handlers/handler_test.go
  handlers/libhoney_event_handler_test.go
  handlers/otel_handler.go
  handlers/otel_handler_test.go
Labels: type: enhancement

#302 docs: Document expected behaviour for event creation
  README.md
Labels: type: documentation, version: no bump

#304 feat: Make OTel handler default
  config/config.go
  config/config_test.go
  smoke-tests/deployment.yaml
Labels: type: enhancement

#306 fix: include OTel semconv 1.20 attributes in spans
  handlers/otel_handler.go
  handlers/otel_handler_test.go
Labels: type: bug

#308 docs: update configs in readme and smoke-test deployment
  README.md
  smoke-tests/deployment.yaml
Labels: type: documentation, version: no bump

#309 rel: prep v0.0.24-alpha
  CHANGELOG.md
  RELEASING.md
  main.go
Labels: no-changelog

#307 fix: improved locking of assembler state
  assemblers/http_matcher.go
  assemblers/tcp_assembler.go
  assemblers/tcp_stream.go
  assemblers/tcp_stream_factory.go
Labels: type: bug, version: bump patch
