Repository honeycombio/honeycomb-network-agent, pull requests merged in 2023-09, with the labels that each got.

#203 maint: Remove unused kernel capabilities and update deployment examples
  DEVELOPING.md
  README.md
  examples/quickstart.yaml
  examples/secret-ghcr.yaml
  smoke-tests/deployment.yaml
Labels: type: maintenance

#212 maint: Make the configuration table clearer
  README.md
Labels: type: maintenance

#198 maint: Remove unused source directory
  source/packet_source.go
Labels: type: maintenance

#216 rel: prep v0.0.17-alpha
  CHANGELOG.md
  main.go
Labels: no-changelog

#157 feat: Update http matcher to use sync.map
  assemblers/http_matcher.go
  assemblers/http_matcher_test.go
  assemblers/tcp_reader.go
Labels: type: enhancement

#210 maint: Refactor Stream and Reader IDs to use uint64/int64
  assemblers/http_event.go
  assemblers/http_matcher.go
  assemblers/http_matcher_test.go
  assemblers/tcp_reader.go
  assemblers/tcp_stream.go
  main.go
Labels: type: maintenance

#225 feat: update to OTel semconv v1.21.0
  main.go
  main_test.go
  utils/k8sutils.go
Labels: type: enhancement

#227 feat: Add agent k8s metadata to events
  config/config.go
  config/config_test.go
  main.go
  smoke-tests/deployment.yaml
Labels: type: enhancement

#232 fix: append agent info to user-agent
  main.go
Labels: type: bug

#220 docs: Replace namespace and secret files with kubectl cmds in README
  DEVELOPING.md
  README.md
  examples/ns.yaml
  examples/secret-honeycomb.yaml
Labels: type: documentation

#226 feat: prefix k8s attributes with source and add more k8s destination attributes
  go.mod
  go.sum
  main.go
  main_test.go
  utils/cached_k8s_client.go
  utils/k8sutils.go
Labels: type: enhancement

#222 maint: Consolidate dockerfiles and update deps
  Dockerfile
  Dockerfile.test
  Makefile
Labels: type: maintenance

#231 maint: Use indexes for looking up cached k8s resources
  utils/cached_k8s_client.go
  utils/k8sutils.go
Labels: type: maintenance

#234 maint: Update gitignore for direnv file names
  .gitignore
Labels: type: maintenance

#199 maint: Remove unused stats and event fields
  assemblers/tcp_assembler.go
Labels: type: maintenance

#238 fix: add a waitgroup to coordinate shutdown
  assemblers/tcp_assembler.go
  handlers/event_handler.go
  handlers/libhoney_event_handler.go
  handlers/libhoney_event_handler_test.go
  main.go
Labels: type: bug

#245 rel: prep v0.0.18-alpha
  CHANGELOG.md
  main.go
Labels: no-changelog

#246 fix: default Dockerfile build to the runnable agent stage
  Dockerfile
  Makefile
Labels: type: bug, version: bump patch

#248 feat: set error field if HTTP status >= 400
  handlers/libhoney_event_handler.go
  handlers/libhoney_event_handler_test.go
Labels: type: enhancement

#256 docs: Add supported k8s platforms to README
  README.md
Labels: type: documentation
